name: Draft Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default_bump: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    inputs:
      bump:
        default_bump: 'patch'

jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Version and Push Tag
        if: github.repository == 'hat-kid/clownfish'
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.tag_version.outputs.new_tag }} --generate-notes --draft --repo hat-kid/clownfish
